import type { LegalDocument } from "../legal-content";

export const privacyPolicy: LegalDocument = {
  slug: "privacy",
  title: "Privacy Policy",
  lede: "How Flacron Energy collects, uses, discloses, stores, and protects the information entrusted to the platform.",
  intro: [
    {
      kind: "p",
      text: "Flacron Energy respects privacy and is committed to protecting personal, professional, operational, and industrial information entrusted to the platform. This Privacy Policy explains how Flacron Energy and its operator, Flacron Enterprises LLC, collect, use, process, disclose, store, and protect information when organizations and authorized users use the Flacron Energy website, applications, dashboards, asset-management tools, AI analysis, AR inspection tools, work orders, safety workflows, permit-to-work tools, reports, 3D visualization, VR training, subscriptions, and related services.",
    },
    { kind: "contact" },
    {
      kind: "p",
      text: "By accessing or using Flacron Energy, you acknowledge the data practices described in this Privacy Policy.",
    },
  ],
  sections: [
    {
      id: "information-we-collect",
      title: "1. Information We Collect",
      blocks: [
        { kind: "p", text: "1.1 Account and Identity Information" },
        {
          kind: "list",
          items: [
            "Full name",
            "Business email address",
            "User ID",
            "Authentication information",
            "Company or organization",
            "Job title",
            "Department",
            "Assigned role and permissions",
            "Subscription or contract status",
            "Login activity",
            "Security information associated with the account",
          ],
        },
        { kind: "p", text: "1.2 Company, Facility and Project Information" },
        {
          kind: "list",
          items: [
            "Company name",
            "Facility/site name",
            "Project name",
            "Business contact information",
            "Facility location",
            "Operational notes",
            "Organization configuration",
            "Assigned users and roles",
          ],
        },
        { kind: "p", text: "1.3 Asset Information" },
        {
          kind: "list",
          items: [
            "Asset names and categories",
            "Manufacturer/model/serial number",
            "Installation date",
            "QR code identifiers",
            "GPS location",
            "Photos and documents",
            "Equipment manuals",
            "3D model references",
            "Inspection history",
            "Maintenance history",
            "Asset status and condition records",
          ],
        },
        { kind: "p", text: "1.4 Inspection and AR Information" },
        {
          kind: "list",
          items: [
            "Inspection checklists",
            "Photos and videos",
            "Damage annotations",
            "AR measurements",
            "Voice notes",
            "GPS tags",
            "Timestamps",
            "Digital signatures",
            "Before/after photos",
            "Inspector observations",
            "Offline inspection data pending synchronization",
          ],
        },
        { kind: "p", text: "1.5 AI Analysis Information" },
        {
          kind: "list",
          items: [
            "Images and videos submitted for analysis",
            "Detected corrosion, rust, cracks, leaks, wear, or visible abnormalities",
            "Confidence scores",
            "Suggested issues and recommended next actions",
            "User confirmations, edits, and overrides",
            "Prompts, instructions, and generated summaries",
          ],
        },
        { kind: "p", text: "1.6 Manual Operational Data" },
        {
          kind: "list",
          items: [
            "Temperature entered manually",
            "Pressure entered manually",
            "Noise observations",
            "Vibration observations",
            "Leak observations",
            "Operational status",
            "Comments",
            "Recommendations",
            "Priority levels",
          ],
        },
        { kind: "p", text: "1.7 Safety and Incident Information" },
        {
          kind: "list",
          items: [
            "Near-miss reports",
            "Unsafe-condition reports",
            "Unsafe-behavior reports",
            "Fire, gas leak, spill, equipment failure, injury, or environmental incident information",
            "Severity",
            "Corrective actions",
            "Media",
            "Location",
            "Reporter",
            "Assigned manager",
            "Status",
          ],
        },
        { kind: "p", text: "1.8 Permit-to-Work Information" },
        {
          kind: "list",
          items: [
            "Permit type",
            "Risk assessments",
            "Checklists",
            "Assigned workers",
            "Approvals",
            "Digital signatures",
            "Activation and closure status",
            "Supporting documentation",
          ],
        },
        { kind: "p", text: "1.9 Work Order and Maintenance Information" },
        {
          kind: "list",
          items: [
            "Asset",
            "Priority",
            "Assigned technician",
            "Due date",
            "Labor hours",
            "Materials used",
            "Repair evidence",
            "Photos/videos",
            "Completion notes",
            "Supervisor review and closure information",
          ],
        },
        { kind: "p", text: "1.10 Reports, Analytics and 3D/VR Usage" },
        {
          kind: "list",
          items: [
            "Generated inspection, maintenance, safety, asset-health, and executive reports",
            "Risk scores",
            "Facility/asset interactions in 3D views",
            "VR training progress and drill activity where enabled",
            "Dashboard and analytics usage",
          ],
        },
        { kind: "p", text: "1.11 Billing and Subscription Information" },
        {
          kind: "list",
          items: [
            "Customer/account identifiers from payment providers",
            "Plan/tier",
            "Facility, asset, and seat allotments",
            "Billing interval",
            "Subscription status",
            "Invoices",
            "Payment status",
            "Renewal date",
            "Cancellation status",
            "Transaction references",
            "Applicable tax information",
          ],
        },
        { kind: "p", text: "1.12 Device, Technical and Security Information" },
        {
          kind: "list",
          items: [
            "IP address",
            "Browser and operating system",
            "Device type",
            "App version",
            "Approximate geographic region",
            "Session and login activity",
            "Feature interactions",
            "Crash and error logs",
            "Performance information",
            "Security events",
            "Fraud or abuse indicators",
          ],
        },
        { kind: "p", text: "1.13 Contact and Support Information" },
        {
          kind: "list",
          items: [
            "Name",
            "Email",
            "Phone number if voluntarily provided",
            "Company",
            "Support category",
            "Message",
            "Attachments",
            "Billing information necessary to investigate a request",
            "Technical information necessary to troubleshoot an issue",
          ],
        },
      ],
    },
    {
      id: "how-we-use-information",
      title: "2. How We Use Information",
      blocks: [
        {
          kind: "list",
          items: [
            "Create and maintain accounts and organizations",
            "Authenticate users and enforce role-based access control",
            "Operate dashboards and task workflows",
            "Manage facilities, assets, projects, QR codes, inspections, permits, work orders, safety reports, and documents",
            "Provide AI-assisted image/video analysis and reporting",
            "Enable AR measurements and annotations",
            "Generate inspection, maintenance, safety, asset-health, and executive reports",
            "Provide static 3D visualization and optional VR training functionality",
            "Send operational, security, billing, and assignment notifications",
            "Process subscriptions and verify entitlement",
            "Maintain audit logs",
            "Detect fraud, abuse, unauthorized access, and security threats",
            "Troubleshoot and improve platform performance",
            "Respond to privacy requests",
            "Comply with law and protect Flacron Enterprises LLC, customers, users, and third parties",
          ],
        },
      ],
    },
    {
      id: "ai-processing",
      title: "3. AI Processing and Human Review",
      blocks: [
        {
          kind: "p",
          text: "Flacron Energy may use artificial intelligence and computer-vision systems to analyze industrial photos, videos, inspection observations, and related operational information. AI output may identify possible corrosion, cracks, leaks, missing components, wear, damage, or other visible abnormalities and may generate confidence scores, summaries, recommendations, or risk-oriented suggestions.",
        },
        {
          kind: "notice",
          title: "Human-in-the-Loop Requirement",
          text: "AI findings are advisory and must not be treated as authoritative engineering, inspection, maintenance, safety, or regulatory determinations. Authorized personnel must be able to review, confirm, modify, or reject AI findings before they are finalized or relied upon.",
          tone: "warning",
        },
      ],
    },
    {
      id: "service-providers",
      title: "4. Service Providers and Information Sharing",
      blocks: [
        {
          kind: "list",
          items: [
            "Cloud infrastructure and hosting",
            "Authentication and identity services",
            "Data storage",
            "Artificial intelligence and computer vision",
            "Email and push notifications",
            "Maps and location services",
            "Payment processing",
            "Analytics and error monitoring",
            "Security and fraud prevention",
            "Document generation",
            "Customer support",
            "3D/AR/VR technology providers where applicable",
          ],
        },
        {
          kind: "p",
          text: "Service providers may process information only as permitted by their agreements with us and applicable law.",
        },
      ],
    },
    {
      id: "legal-disclosures",
      title: "5. Legal, Safety and Corporate Disclosures",
      blocks: [
        {
          kind: "list",
          items: [
            "Comply with applicable law or valid legal process",
            "Protect life, safety, property, users, and systems",
            "Investigate fraud, misuse, or security incidents",
            "Enforce agreements and platform rules",
            "Respond to regulatory or governmental requests where legally required",
            "Support a merger, acquisition, financing, reorganization, or sale of assets subject to appropriate safeguards",
          ],
        },
      ],
    },
    {
      id: "data-retention",
      title: "6. Data Retention",
      blocks: [
        {
          kind: "p",
          text: "Flacron Energy may retain account, operational, inspection, safety, maintenance, billing, audit, and security information for as long as reasonably necessary to provide the service, satisfy contractual obligations, preserve industrial records, resolve disputes, maintain safety or compliance records, prevent fraud, meet accounting requirements, and comply with applicable law. Retention periods may differ by data category, customer contract, jurisdiction, and industry requirement.",
        },
      ],
    },
    {
      id: "security",
      title: "7. Security",
      blocks: [
        {
          kind: "list",
          items: [
            "Server-side authentication and authorization",
            "Role-based access control",
            "Tenant/company data isolation",
            "Encryption where appropriate",
            "Secure cloud infrastructure",
            "Controlled administrative access",
            "Rate limiting",
            "Audit logs for critical actions",
            "Protected API keys and secrets",
            "Access-controlled uploaded media and documents",
            "Monitoring and incident response",
            "Payment-provider security controls",
          ],
        },
        { kind: "p", text: "No internet-connected service can guarantee absolute security." },
      ],
    },
    {
      id: "privacy-rights",
      title: "8. Privacy Rights",
      blocks: [
        {
          kind: "list",
          items: [
            "Request access to applicable personal information",
            "Request correction",
            "Request deletion where applicable",
            "Obtain certain copies of information",
            "Withdraw consent where processing depends on consent",
            "Object to or restrict certain processing where applicable",
            "Opt out of certain marketing communications",
            "Exercise applicable rights concerning targeted advertising, sharing, or similar regulated activities",
          ],
        },
        {
          kind: "p",
          text: "Requests may be submitted to Contact@flacronenterprises.com. We may need to verify identity and organizational authority before completing certain requests.",
        },
      ],
    },
    {
      id: "international",
      title: "9. International and Enterprise Users",
      blocks: [
        {
          kind: "p",
          text: "Flacron Energy may serve customers and users in multiple countries. Data may be processed in jurisdictions different from the user's location. Enterprise customers may also impose contractual, security, data-residency, retention, or access-control requirements. Where required, appropriate safeguards should be implemented.",
        },
      ],
    },
    {
      id: "children",
      title: "10. Children",
      blocks: [
        {
          kind: "p",
          text: "Flacron Energy is an enterprise industrial platform and is not intended for children. Users must have the legal capacity and organizational authorization necessary to use the service.",
        },
      ],
    },
    {
      id: "changes-and-contact",
      title: "11. Changes and Contact",
      blocks: [
        {
          kind: "p",
          text: "We may update this Privacy Policy periodically. The current version should display its latest update date. Material changes may be communicated by email, in-product notice, contract notice, or renewed acceptance where appropriate.",
        },
        { kind: "contact" },
      ],
    },
  ],
};
