name: fev_mobile
description: Flacron EnergyVerse Field App
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  dio: 5.7.0
  fev_api_client:
    path: ../../packages/contracts/generated/dart-dio
  shared_preferences: 2.3.2
  firebase_core: 4.12.1
  firebase_auth: 6.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Variable.ttf
